name: Deploy (prod)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer
        extensions: mbstring, intl, curl, zip

    # >>> PENTING: JANGAN --no-dev (agar Deployer terpasang di vendor)
    - name: Install dependencies (with dev)
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Start ssh-agent and add key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add known_hosts (host key)
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

    - name: Sanity check - list keys loaded
      run: ssh-add -l

    - name: Sanity check - try SSH to server (no command)
      run: |
        ssh -vvv -o StrictHostKeyChecking=yes -p "${{ secrets.SSH_PORT }}" \
          "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" true

    - name: Deploy (vendor/bin/dep)
      run: vendor/bin/dep deploy -vvv --no-interaction
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        BRANCH: ${{ secrets.BRANCH }}
