name: Deploy (prod)

on:
  push:
    branches: [ "main" ]  # sesuaikan
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
          extensions: mbstring, intl, curl, zip

      - name: Install dependencies (no-dev)
        run: composer install --no-dev --prefer-dist --no-progress --no-interaction

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      # (Opsional tapi dianjurkan) tambah host key agar StrictHostKeyChecking tidak error
      - name: Add known_hosts
        run: |
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      # Cara A (direkomendasikan): gunakan action resmi Deployer untuk menjalankan 'dep deploy'
      - name: Run Deployer
        uses: deployphp/action@v1
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          BRANCH: ${{ secrets.BRANCH }}
        with:
          dep: deploy
          php-binary: "php"
          composer: "composer"

      # Cara B (alternatif manual): jalankan perintah dep langsung
      # - name: Deploy (manual)
      #   run: vendor/bin/dep deploy -vvv
      #   env:
      #     SSH_HOST: ${{ secrets.SSH_HOST }}
      #     SSH_USER: ${{ secrets.SSH_USER }}
      #     SSH_PORT: ${{ secrets.SSH_PORT }}
      #     DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      #     BRANCH: ${{ secrets.BRANCH }}
